### ISSUE TITLE
OSS License on this project

### ISSUE THREAD

**Issue by gabceb** [tomscholz/Better-GeoJson-Editor#7]
First, Thanks for all your work on this project @tomscholz.

Would it be possible to add an OSS license so it can be appropriately used by others? Github has some documentation on https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository and I personally like https://tldrlegal.com/

**Comment by tomscholz** [comment]
Took a while, but it's done now.
